#!/bin/bash
origfolderdirectory=${PWD} # This is the original folder directory path.
origfoldername=${PWD##*/} # This is the original folder name.
mkdir -p Temp # This creates a temp folder where all the temporary files will stay.
find . -name "*.mp4" >> ./Temp/files.txt # This grabs a list of all .mp4 files and puts the output into files.txt
cd Temp # Changes directory to Temp.
cat files.txt | sed 's/^..//' > fileswithoutdot.txt # This removes the dots from the start of every line in files.txt and outputs fileswithoutdot.txt
cat fileswithoutdot.txt | sed -e "s#^#$origfolderdirectory#g" > prefixfiles.txt # This adds the original folder name to the start of each line in fileswithoutdot.txt and outputs to prefixfiles.txt
cat prefixfiles.txt | sed -e "s#$origfoldername#Encoded./$origfoldername./#" > prefixedfiles.txt # This adds ../Encoded. to the start of every line in prefixfiles.txt and outputs to prefixedfiles.txt
cd ../ # Backs out of Temp folder
find . -type d -exec mkdir -p -- ../Encoded./$origfoldername{} \; # Copies folder structure of $origfoldername to ../Encoded.
rm -r ../Encoded./$origfoldername./Temp # Removes temp folder from ../Encoded
files=$(cat ./Temp/files.txt)
prefixedfiles=$(cat ./Temp/prefixedfiles.txt)
echo "$files" >> generatedscript
sed -e 's/^/ffmpeg -i /' generatedscript >> generatedscript2
sed 's/$/ -vcodec libx264 -acodec copy -threads 10 -crf 18 /' >> generatedscript2
echo "$prefixedfiles"